version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - 3600:27017
  bot:
    image: eoussama/salim-the-mayonnaise-finger:bot-0.0.1
    build:
      context: ./src/bot/
      dockerfile: Dockerfile
    env_file: ./src/bot/.env
  web:
    image: eoussama/salim-the-mayonnaise-finger:web-0.0.1
    build:
      context: ./src/web/
      dockerfile: Dockerfile
